#Robot Properties
robocode.version=1.11.0
robot.description=MechGarden Proteus, a self-contained adaptive 1v1 robot.
robot.webpage=
robot.author.name=Zhang Erning
robot.classname=zen.Proteus
robot.name=Proteus
robot.version=0.8.0
