#Robot Properties
robocode.version=1.11.0
robot.description=MechGarden Mirage, a self-contained defensive Robocode 1v1 robot.
robot.webpage=
robot.author.name=Zhang Erning
robot.classname=zen.Mirage
robot.name=Mirage
robot.version=0.1.0
